name: Gitleaks scan

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gitleaks (via Docker image)
        run: |
          echo "Running gitleaks docker image"
          docker run --rm -v "${{ github.workspace }}:/src" ghcr.io/zricethezav/gitleaks:8.4.0 detect --source=/src --config=/src/.gitleaks.toml --verbose